### ISSUE TITLE
I Can't get it to run...

### ISSUE THREAD

**Issue by Juniornativa** [pramod-rathod-avalara/startbootstrap-sb-admin-2-sidebar-toggle#1]
I'm having problems, i've just downloaded these files and replaced the files into the root template folder, but it's not working... How should i do?

Thanks buddy, and congrats!!

**Comment by pramod-rathod-avalara** [comment]
Hi Juniornativa ,

If you are replacing the files into the 'StartBootstrap SB Admin 2' template folder. Things will not work as is. You will need to correct the paths to CSS and JS files into the index.html. The index.html in the downloaded project by default points to './assets/bower/' and './assets/css' folder.

Instead just include the ./assets/css/sbadmin2-sidebar-toggle.css into your template project and update the index.html to as per. The things to look for are inside index.html are contents inside <div id="sidebar-wrapper"> and <span class="masked">.

I hope this helps!

**Comment by Juniornativa** [comment]
Hi my friend, i have a really big problem...

I'm having problem running the template on Mozilla Firefox, bootstrap table
plugin is not responding to the screen sizes when the sidebar menu is
expanded

and so broking the layout...

2015-06-26 15:59 GMT-03:00 pramod.rathod notifications@github.com:
