### ISSUE TITLE
Mozilla Firefox Problem...

### ISSUE THREAD

**Issue by Juniornativa** [pramod-rathod-avalara/startbootstrap-sb-admin-2-sidebar-toggle#5]
I'm having problem running the template on Mozilla Firefox, bootstrap table plugin is not responding to the screen sizes when the sidebar menu is expanded
![template error](https://cloud.githubusercontent.com/assets/6595338/8532087/2af0343a-2402-11e5-9408-c7f68dda7e5a.png)
, and so broking the layout...

**Comment by pramod-rathod-avalara** [comment]
Hi,

I have fixed a few layout issues in version 0.0.4.

What version of the sbadmin2-sidebar-toggle.css are you using? 

This how it looks on firefox when I tested locally. 

![1336x768](https://cloud.githubusercontent.com/assets/8553770/8539639/b4fd9cf0-249b-11e5-867e-2d87f41dcc93.png)

~ Pramod

**Comment by Juniornativa** [comment]
I'm using the 0.0.2 version...
Where can i find the latest one?

**Comment by Juniornativa** [comment]
I've just found the latest version, it worked like a charm.. every problem solved..
Thanks so much bro, i'm happy now haha!
I'm not a front-end developer but i'm inspired by people like you!!
Thanks

**Comment by Juniornativa** [comment]
I've just found the latest version, it worked like a charm.. every problem solved..
Thanks so much bro, i'm happy now haha!
I'm not a front-end developer but i'm inspired by people like you!!
Thanks

**Comment by Juniornativa** [comment]
I've just found the latest version, it worked like a charm.. every problem solved..
Thanks so much bro, i'm happy now haha!
I'm not a front-end developer but i'm inspired by people like you!!
Thanks

**Comment by pramod-rathod-avalara** [comment]
Awesome !!
